// GENERATED FILE — run: flutterfire configure
// After running `flutterfire configure`, this file is auto-generated.
// See SETUP.md Step 3 for instructions.
//
// DO NOT edit this file manually. Delete it and run `flutterfire configure` again.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not supported.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError('Unsupported platform.');
    }
  }

  // ⚠️  Replace this with values from your google-services.json

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCucN-eWRh5vvOvtF6FTkNsM7DB76F9Tv4',
    appId: '1:286375808948:android:4fc732fa649515b16f6ce1',
    messagingSenderId: '286375808948',
    projectId: 'mindbreak-66378',
    storageBucket: 'mindbreak-66378.firebasestorage.app',
  );

  // Run `flutterfire configure` to auto-generate this correctly.
}